-- Migration: 013_create_resilience_analysis.sql
-- Description: Create tables for resilience analysis engine
-- Created: 2026-06-17

-- Enable UUID extension if not exists
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- Table: resilience_analyses
-- ============================================================================
-- Stores resilience analysis results for individual assets.
-- This table is read-only from the perspective of operational systems.
-- It is populated only by the Resilience Analysis Engine.
-- ============================================================================

CREATE TABLE IF NOT EXISTS resilience_analyses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    asset_id UUID NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    
    -- Scoring metrics (0-100 scale)
    criticality_score FLOAT NOT NULL DEFAULT 0,
    resilience_score FLOAT NOT NULL DEFAULT 100,
    
    -- Dependency counts
    dependency_count INTEGER NOT NULL DEFAULT 0,
    upstream_count INTEGER NOT NULL DEFAULT 0,
    downstream_count INTEGER NOT NULL DEFAULT 0,
    
    -- Risk indicators
    single_point_of_failure BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_resilience_analyses_asset_id 
    ON resilience_analyses(asset_id);

CREATE INDEX IF NOT EXISTS idx_resilience_analyses_criticality_score 
    ON resilience_analyses(criticality_score DESC);

CREATE INDEX IF NOT EXISTS idx_resilience_analyses_resilience_score 
    ON resilience_analyses(resilience_score ASC);

CREATE INDEX IF NOT EXISTS idx_resilience_analyses_spof 
    ON resilience_analyses(single_point_of_failure) 
    WHERE single_point_of_failure = TRUE;

-- ============================================================================
-- Table: resilience_recommendations
-- ============================================================================
-- Stores recommendations generated by the resilience analysis engine.
-- Each recommendation is tied to a specific analysis.
-- ============================================================================

CREATE TABLE IF NOT EXISTS resilience_recommendations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    analysis_id UUID NOT NULL REFERENCES resilience_analyses(id) ON DELETE CASCADE,
    
    -- Recommendation metadata
    recommendation_type VARCHAR(50) NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    description TEXT NOT NULL,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_resilience_recommendations_analysis_id 
    ON resilience_recommendations(analysis_id);

CREATE INDEX IF NOT EXISTS idx_resilience_recommendations_priority 
    ON resilience_recommendations(priority);

CREATE INDEX IF NOT EXISTS idx_resilience_recommendations_type 
    ON resilience_recommendations(recommendation_type);

-- ============================================================================
-- Comments for documentation
-- ============================================================================

COMMENT ON TABLE resilience_analyses IS 
    'Stores resilience analysis results for assets. Read-only from operational systems.';

COMMENT ON TABLE resilience_recommendations IS 
    'Stores recommendations generated by the resilience analysis engine.';

COMMENT ON COLUMN resilience_analyses.criticality_score IS 
    'Asset criticality score (0-100). Higher = more critical to network.';

COMMENT ON COLUMN resilience_analyses.resilience_score IS 
    'Asset resilience score (0-100). Higher = more resilient to failures.';

COMMENT ON COLUMN resilience_analyses.single_point_of_failure IS 
    'TRUE if removing this asset disconnects multiple downstream branches.';

COMMENT ON COLUMN resilience_analyses.dependency_count IS 
    'Number of direct dependencies this asset has.';

COMMENT ON COLUMN resilience_recommendations.recommendation_type IS 
    'Type: redundancy, monitoring, backup, failover, maintenance, diversification';
