"""
Resilience Recommendation Model

Stores recommendations generated by the resilience analysis engine.
"""

from sqlalchemy import Column, String, Text, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from backend.src.database.config import Base


class RecommendationPriority(str):
    """Recommendation priority levels."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecommendationType(str):
    """Types of resilience recommendations."""
    REDUNDANCY = "redundancy"
    MONITORING = "monitoring"
    BACKUP = "backup"
    FAILOVER = "failover"
    MAINTENANCE = "maintenance"
    DIVERSIFICATION = "diversification"
    RECONFIGURATION = "reconfiguration"
    EARLY_WARNING = "early_warning"


class ResilienceRecommendation(Base):
    """
    Stores a recommendation for improving asset resilience.
    
    Generated by the Resilience Analysis Engine based on
    criticality and resilience calculations.
    """
    
    __tablename__ = "resilience_recommendations"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    analysis_id = Column(
        UUID(as_uuid=True), 
        ForeignKey("resilience_analyses.id", ondelete="CASCADE"), 
        nullable=False
    )
    
    # Recommendation metadata
    recommendation_type = Column(String(50), nullable=False)
    priority = Column(String(20), nullable=False, default=RecommendationPriority.MEDIUM)
    description = Column(Text, nullable=False)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow)
    
    # Relationships
    analysis = relationship("ResilienceAnalysis", back_populates="recommendations")
    
    def __repr__(self):
        return f"<ResilienceRecommendation(id={self.id}, type={self.recommendation_type}, priority={self.priority})>"
    
    def to_dict(self):
        return {
            "id": str(self.id),
            "analysis_id": str(self.analysis_id),
            "recommendation_type": self.recommendation_type,
            "priority": self.priority,
            "description": self.description,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
